# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kurt's Hurricanes
email: kbooze97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Anything tropical! this will be a blog committed to all things tropical in the Atlantic hurricane basin, or anything
   exceptionally strong or odd in any basin. This is my first website, so it may have many glitches and bugs, but I
   will try my best to not have any.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kbooze.github.io/" # the base hostname & protocol for your site
twitter_username: <a href="https://twitter.com/Rockbandawesome" target="_blank">My Twitter</a>

# Build settings
markdown: kramdown
